swagger: "2.0"

info:
  title: Scheduled Task
  description: Simple script executed like Cronjob
  version: 1.0.0

x-app-info:
  type: AWS::EventBridge::Rule
  name: "demo-cronjob-01"


x-lambda:
  - name: "lambda-demo-periodic-run"
    runtime: python3.8
    arch: x86_64
    handler: application.services.service3.lambda_handlers.handler
    role-name: "Lambda-General-Execution-Role"
    layers:
      - type: python-requirements
        manifest: ./application/services/service3/requirements.txt
    upload-ignore:
      - iam/*
      - utils/*
      - scripts/*


x-schedules:
  schedule1:
    name: 'demo-schedule-001'
    cron: "rate(1 day)"
    x-lambda-name: "lambda-demo-periodic-run"
